### ISSUE TITLE
Broken links to XML examples in REST API documentation.

### ISSUE THREAD

**Issue by PGijsbers** [openml/docs#20]
In the [api docs](https://new.openml.org/api) there are some broken links. So far, I found:
 - `run/trace/{id}`'s [example](https://www.openml.org/api/v1/xml_example/run.trace)
 - `run/evaluate`'s [example](https://www.openml.org/api/v1/xml_example/run.evaluate)

**Comment by joaquinvanschoren** [comment]
Added these.
