### ISSUE TITLE
"API Reference" links are dead

### ISSUE THREAD

**Issue by mb706** [openml/docs#21]
The links on [this page](https://docs.openml.org/REST-API/) currently lead to nowhere.

**Comment by joaquinvanschoren** [comment]
Thanks!
I've done a full pass over the documentation pages, updated the entire BootCamp page, and cleaner up deprecated parts.

The API docs were moved here: https://www.openml.org/apis

**Comment by PGijsbers** [comment]
@mb706 where did you get that link from? Maybe we can update the source that got you there, or potentially we need to add a redirect.

**Comment by mb706** [comment]
The page is e.g. reachable through the "REST API Reference" link on [this page](https://docs.openml.org/APIs/), which again is reached from the "APIs and client libraries" link [here](https://docs.openml.org/benchmark/). It is also reachable when searching for API in the search box.

**Comment by mb706** [comment]
Btw, the link at the very bottom of the main page (https://docs.openml.org/) (with the text "This key can then be used with any of the *OpenML APIs*") also links to the https://docs.openml.org/APIs/.

**Comment by joaquinvanschoren** [comment]
I added a note with the link to the new documentation on that page. Pieter has updated the old links. Are we ok now?
