### ISSUE TITLE
404 fetched by Communication-Channels page in Docs

### ISSUE THREAD

**Issue by mach-12** [openml/docs#30]
The [Communication-Channels](https://docs.openml.org/Contributing/Communication-Channels) page returns _404 - Not Found_
Despite having the following [Communication-Channels.md](https://github.com/openml/docs/blob/master/docs/Communication-Channels.md) file in the [Docs](https://github.com/openml/docs/).
<img width="905" alt="image" src="https://github.com/openml/docs/assets/89384052/ca04f485-5bca-4d34-b0d8-797b72c3ca97">

**Comment by mach-12** [comment]
The url is https://docs.openml.org/Contributing/#Communication-Channels. Apologies for posting this.
Requesting for the admins to remove this.

**Comment by joaquinvanschoren** [comment]
No worries :)
