### ISSUE TITLE
Location of contributing guide

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/docs#6]
The contributing guide is currently under tab `Bootcamp` rather than tab `Developers`. 

![image](https://user-images.githubusercontent.com/14146757/97182103-6282ac00-179c-11eb-8426-83045e858069.png)

Is this what we want? Should we at least add a link from the "Contributing" section in tab `Developers` to the contributing guide? What do you think is best?

![image](https://user-images.githubusercontent.com/14146757/97182283-a5dd1a80-179c-11eb-84f9-4573ce7b5057.png)

**Comment by joaquinvanschoren** [comment]
I'd be OK to move it to Developers. Actually I think we can merge the content with the welcome page there.
Shall I do a PR? I'm working on docs anyway right now.

**Comment by HeidiSeibold** [comment]
Sounds great!

**Comment by HeidiSeibold** [comment]
Maybe we should add a link somewhere in Community to the contributing guide to make it easy to find

**Comment by joaquinvanschoren** [comment]
I think we can close this one? Please reopen if not.

**Comment by HeidiSeibold** [comment]
I'd do one more thing, see https://github.com/openml/OpenML/pull/1070
